name: smartrouter
services:
- name: ingress
  image: docker.io/nginx
  bindings:
    - protocol: http
      port: 8080
  volumes:
    - source: nginx.conf
      target: /etc/nginx/conf.d/default.conf
- name: sample
  project: Snowflake.Redis.Sample/Snowflake.Redis.Sample.csproj
  replicas: 2
- name: redis
  image: docker.io/redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}"
